#!/bin/sh
#
# @name Airboat
#
#
# @type Rover
# @class Rover
#
#
# @output MAIN0 Speed of left wheels
# @output MAIN1 Speed of right wheels
# @output MAIN2 Speed of left wheels
# @output MAIN3 Speed of right wheels
#
# @maintainer Fournet Fabien
#

sh /etc/init.d/rc.rover_defaults

if [ $AUTOCNF = yes ]
then
	param set BAT_N_CELLS 4

fi

# Start this driver after setting parameters, because the driver uses some of those parameters.
# roboclaw start /dev/ttyS3

# Configure this as rover
set MAV_TYPE 10

# Set mixer
set MIXER airboat

