#!/bin/sh
#
# @name airboat 6
#
#
# @type Rover
# @class Rover
#
# @board px4_fmu-v5 exclude
#
# @output MAIN0 Speed of left wheels
# @output MAIN1 Speed of right wheels
# @output MAIN2 Speed of left wheels
# @output MAIN3 Speed of right wheels
#
# @maintainer Fournet Fabien
#
# @board px4_fmu-v5 exclude
#

set PWM_OUT 1234

sh /etc/init.d/rc.rover_defaults

if [ $AUTOCNF = yes ]
then
	# The set does not include a battery, but most people will probably use 4S
	param set BAT_N_CELLS 6
	param set PWM_MAX 1900
	param set PWM_MIN 1050

	param set PWM_RATE 1490
	
fi

set MIXER_AUX pass
set PWM_AUX_OUT 1234

set MAV_TYPE 10

# Set mixer
set MIXER airboat
