#!/bin/sh
#
# @name Airboat
#
#
# @type Quadrotor x
# @class Copter
#
#
# @output MAIN0 Speed of left wheels
# @output MAIN1 Speed of right wheels
# @output MAIN2 Speed of left wheels
# @output MAIN3 Speed of right wheels
#
# @maintainer Fournet Fabien
#

sh /etc/init.d/rc.mc_defaults

set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	# The set does not include a battery, but most people will probably use 4S
	param set BAT_N_CELLS 6
	param set PWM_MAX 1950
	param set PWM_MIN 1050

	param set PWM_RATE 0
	
fi

set MAV_TYPE 2

# Set mixer
set MIXER airboat
