#!/bin/sh
#
# @name Airboat
#
#
# @type Rover
# @class Rover
#
#
# @output MAIN0 Speed of left wheels
# @output MAIN1 Speed of right wheels
# @output MAIN2 Speed of left wheels
# @output MAIN3 Speed of right wheels
#
# @maintainer Fournet Fabien
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set BAT_N_CELLS 6

	param set PWM_MAX 1950
	param set PWM_MIN 1050

	param set PWM_RATE 0


# Set mixer
set MIXER airboat
